name: Major Version Sync
description: Syncs the major version tag with the current tag.

branding:
  icon: tag
  color: gray-dark

inputs:
  token:
    description: |-
      The GitHub token to use for pushing the tag.
    required: false
    default: ${{ github.token }}

outputs:
  tag:
    description: The major version tag.

runs:
  using: node20
  main: dist/index.js
