name: Major Version Sync
run-name: Major Version Sync - ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  major-version-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ github.token }}
