name: Major Version Sync
run-name: Major Version Sync - ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  major-version-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./
        with:
          token: ${{ github.token }}
