name: Update tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Get tag info
        id: tag
        run: |
          echo "current-tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "major-tag=$(echo ${{ github.ref_name }} | cut -d . -f 1)" >> $GITHUB_OUTPUT

      - name: Update or create major version tag
        env:
          CURRENT_TAG: ${{ steps.tag.outputs.current-tag }}
          MAJOR_TAG: ${{ steps.tag.outputs.major-tag }}
        run: |
          git tag --force "${MAJOR_TAG}" "${CURRENT_TAG}"
          git push origin "${MAJOR_TAG}" --force
